# Generated by Django 3.0.8 on 2020-07-19 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_auto_20200712_1213'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='bedooms',
            new_name='bedrooms',
        ),
    ]
